version: '3.8'

services:
  vectorimo-postgres:
    container_name: vectorimo-postgres
    image: postgres
    restart: always
    build:
      context: ./postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
