version: '3.8'

services:
  vectorimo-postgres:
    container_name: vectorimo-postgres
    image: postgres
    restart: always
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data:delegated
    ports:
      - "5432:5432"
