name: Run unit tests and coverage report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.2
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install coverage

      - name: Wait for PostgreSQL to start
        run: docker ps && sleep 5

      - name: Create test database
        env:
          PGPASSWORD: postgres
        run: psql -h localhost -U postgres -c "CREATE DATABASE test_db;"


      - name: Run tests with coverage
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
        run: |
          coverage run -m unittest discover -s tests -p '*.py'
          coverage report

      - name: Run code coverage
        run: |
          python -m pip install coveralls
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}